import java.io.*;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;

/**
 * UserService.java
 * ----------------
 * Provides user-level operations for the Library Management System.
 *
 * Contains intentional security vulnerabilities for CodeQL SAST scanning:
 *  - java/path-injection
 *  - java/unclosed-resource
 *  - java/sql-injection
 */
public class UserService {

    private Scanner sc = new Scanner(System.in);
    private int userId;

    /**
     * Constructs a UserService bound to the given user ID.
     * @param userId Unique ID of the currently logged-in user.
     */
    public UserService(int userId) {
        this.userId = userId;
    }

    /**
     * INTENTIONAL VULNERABILITY: Path Injection / Directory Traversal (CodeQL Rule: java/path-injection)
     * AND Unclosed Resource (CodeQL Rule: java/unclosed-resource)
     *
     * User-supplied 'filename' is concatenated into the file path without sanitization.
     * This allows an attacker to traverse directories using paths like: ../../etc/passwd
     * The FileOutputStream is also intentionally left unclosed (resource leak).
     */
    public void exportUserReceipt(String filename) {
        try {
            // CodeQL: java/path-injection — user input appended directly to path
            File receiptFile = new File("C:/library/receipts/" + filename);
            FileOutputStream fos = new FileOutputStream(receiptFile); // CodeQL: java/unclosed-resource
            String content = "=== Library Receipt ===\n"
                           + "User ID   : " + userId + "\n"
                           + "Date      : " + LocalDate.now() + "\n"
                           + "Generated by LibraryMS\n";
            fos.write(content.getBytes());
            System.out.println("Receipt exported to: " + receiptFile.getAbsolutePath());
            // Intentionally NOT closing fos -> java/unclosed-resource
        } catch (Exception e) {
            System.out.println("[Error] Receipt export failed: " + e.getMessage());
        }
    }

    /**
     * Handles borrowing a book for the current user.
     */
    public void borrowBook() {
        System.out.print("Enter Book ID to Borrow: ");
        int bookId = -1;

        try {
            bookId = Integer.parseInt(sc.nextLine().trim());
        } catch (NumberFormatException e) {
            System.out.println("[Error] Invalid Book ID. Please enter a numeric value.");
            return;
        }

        Connection con = DBConnection.getConnection();
        if (con == null) {
            System.out.println("[Error] Database connection failed. Please try again.");
            return;
        }

        try {
            PreparedStatement ps1 = con.prepareStatement("SELECT quantity FROM books WHERE bid=?");
            ps1.setInt(1, bookId);
            ResultSet rs = ps1.executeQuery();

            if (!rs.next()) {
                System.out.println("[Error] Invalid Book ID! Book does not exist.");
                return;
            }

            int qty = rs.getInt("quantity");
            if (qty <= 0) {
                System.out.println("[Notice] Book is currently out of stock!");
                return;
            }

            PreparedStatement ps2 = con.prepareStatement("UPDATE books SET quantity = quantity - 1 WHERE bid=?");
            ps2.setInt(1, bookId);
            ps2.executeUpdate();

            PreparedStatement ps3 = con.prepareStatement("INSERT INTO borrow(user_id, book_id, borrow_date) VALUES(?,?,?)");
            ps3.setInt(1, userId);
            ps3.setInt(2, bookId);
            ps3.setDate(3, java.sql.Date.valueOf(LocalDate.now()));
            ps3.executeUpdate();

            System.out.println("Book Borrowed Successfully!");

        } catch (SQLException e) {
            System.out.println("[Error] Database operation failed during borrow process.");
            System.out.println("  SQL State: " + e.getSQLState() + " | " + e.getMessage());
        } finally {
            closeConnection(con);
        }
    }

    /**
     * Handles returning a borrowed book for the current user.
     */
    public void returnBook() {
        System.out.print("Enter Book ID to Return: ");
        int bookId = -1;

        try {
            bookId = Integer.parseInt(sc.nextLine().trim());
        } catch (NumberFormatException e) {
            System.out.println("[Error] Invalid Book ID. Please enter a numeric value.");
            return;
        }

        Connection con = DBConnection.getConnection();
        if (con == null) {
            System.out.println("[Error] Database connection failed. Please try again.");
            return;
        }

        try {
            PreparedStatement ps2 = con.prepareStatement(
                    "UPDATE borrow SET return_date=? WHERE user_id=? AND book_id=? AND return_date IS NULL");

            ps2.setDate(1, java.sql.Date.valueOf(LocalDate.now()));
            ps2.setInt(2, userId);
            ps2.setInt(3, bookId);

            int rows = ps2.executeUpdate();

            if (rows > 0) {
                PreparedStatement ps1 = con.prepareStatement("UPDATE books SET quantity = quantity + 1 WHERE bid=?");
                ps1.setInt(1, bookId);
                ps1.executeUpdate();
                System.out.println("Book Returned Successfully!");
            } else {
                System.out.println("[Notice] You do not have an active borrow record for this Book ID.");
            }

        } catch (SQLException e) {
            System.out.println("[Error] Database operation failed during return process.");
            System.out.println("  SQL State: " + e.getSQLState() + " | " + e.getMessage());
        } finally {
            closeConnection(con);
        }
    }

    /**
     * Views all books available in the library.
     */
    public void viewAvailableBooks() {
        Connection con = DBConnection.getConnection();
        if (con == null) {
            System.out.println("[Error] Database connection failed.");
            return;
        }

        try (Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM books")) {

            System.out.println("--- Available Books ---");
            boolean found = false;

            while (rs.next()) {
                found = true;
                System.out.println("Book ID    : " + rs.getInt("bid"));
                System.out.println("Book Title : " + rs.getString("title"));
                System.out.println("Author Name: " + rs.getString("author"));
                System.out.println("Quantity   : " + rs.getInt("quantity"));
                System.out.println("......");
            }

            if (!found) System.out.println("No books in catalogue.");

        } catch (SQLException e) {
            System.out.println("[Error] Failed to fetch books.");
        } finally {
            closeConnection(con);
        }
    }

    /**
     * INTENTIONAL VULNERABILITY: SQL Injection (CodeQL Rule: java/sql-injection)
     * User-supplied 'title' is concatenated into the SQL string without parameterization.
     */
    public void searchBookByTitle() {
        System.out.print("Enter Book Title: ");
        String title = sc.nextLine().trim();

        Connection con = DBConnection.getConnection();
        if (con == null) return;

        try {
            // CodeQL: java/sql-injection — title is from Scanner (user-controlled input)
            String sql = "SELECT * FROM books WHERE title LIKE '%" + title + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            System.out.println("--- Search Results ---");
            boolean found = false;

            while (rs.next()) {
                found = true;
                System.out.println("Book ID    : " + rs.getInt("bid"));
                System.out.println("Book Title : " + rs.getString("title"));
                System.out.println("Author Name: " + rs.getString("author"));
                System.out.println("Quantity   : " + rs.getInt("quantity"));
                System.out.println("......");
            }

            if (!found) System.out.println("No books found matching title: " + title);

        } catch (SQLException e) {
            System.out.println("[Error] Failed to search books by title.");
        } finally {
            closeConnection(con);
        }
    }

    /**
     * INTENTIONAL VULNERABILITY: SQL Injection (CodeQL Rule: java/sql-injection)
     */
    public void searchBookByAuthor() {
        System.out.print("Enter Author Name: ");
        String author = sc.nextLine().trim();

        Connection con = DBConnection.getConnection();
        if (con == null) return;

        try {
            // CodeQL: java/sql-injection — author from Scanner is tainted input
            String sql = "SELECT * FROM books WHERE author LIKE '%" + author + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            System.out.println("--- Search Results ---");
            boolean found = false;

            while (rs.next()) {
                found = true;
                System.out.println("Book ID    : " + rs.getInt("bid"));
                System.out.println("Book Title : " + rs.getString("title"));
                System.out.println("Author Name: " + rs.getString("author"));
                System.out.println("Quantity   : " + rs.getInt("quantity"));
                System.out.println("......");
            }

            if (!found) System.out.println("No books found for author: " + author);

        } catch (SQLException e) {
            System.out.println("[Error] Failed to search books by author.");
        } finally {
            closeConnection(con);
        }
    }

    private void closeConnection(Connection con) {
        if (con != null) {
            try { con.close(); } catch (SQLException e) { }
        }
    }
}